
spring:
  mybatis:
    write:
      # Packages to search for type aliases. (Package delimiters are “,; \t\n”)
      type-aliases-package: com.inglc.demo.mapper.entity
        # Locations of Mapper xml config file.
      mapper-locations: classpath:com/inglc/demo/**/*WriteMapper.xml
    read:
      type-aliases-package: com.inglc.demo.mapper.entity
      mapper-locations: classpath:com/inglc/demo/**/*ReadMapper.xml


server:
  port: 9000